// packages/react/src/HSkeleton.tsx
import type { HTMLAttributes } from 'react'
import type { SkeletonContract } from '@demo/ui-core'

export interface HSkeletonProps extends SkeletonContract, HTMLAttributes<HTMLDivElement> {}

export function HSkeleton({
  width = '100%',
  height = '1rem',
  circle,
  animated = true,
  className,
  style,
  ...props
}: HSkeletonProps) {
  return (
    <div
      {...props}
      className={['ui-skeleton', circle ? 'ui-skeleton--circle' : '', animated ? 'ui-skeleton--animated' : '', className].filter(Boolean).join(' ')}
      style={{ width: circle ? height : width, height, ...style }}
      aria-hidden
    />
  )
}

// packages/web-components/src/h-skeleton.ts
import type { SkeletonContract } from '@demo/ui-core'
import { defineOnce } from './compound'

export class HSkeleton extends HTMLElement {
  static observedAttributes = ['width', 'height', 'circle', 'animated']

  connectedCallback() {
    this.apply()
  }

  attributeChangedCallback() {
    this.apply()
  }

  private apply() {
    const width = this.getAttribute('width') ?? '100%'
    const height = this.getAttribute('height') ?? '1rem'
    const circle = this.hasAttribute('circle')
    const animated = this.getAttribute('animated') !== 'false'
    this.classList.add('ui-skeleton')
    this.classList.toggle('ui-skeleton--circle', circle)
    this.classList.toggle('ui-skeleton--animated', animated)
    this.style.width = circle ? height : width
    this.style.height = height
    this.setAttribute('aria-hidden', 'true')
  }
}

export type HSkeletonProps = SkeletonContract
defineOnce('h-skeleton', HSkeleton)
