// packages/react/src/HVStack.tsx
import type { HTMLAttributes, PropsWithChildren } from 'react'
import type { VStackContract } from '@demo/ui-core'
import { stackClassName, stackStyle } from './layout-style'

export interface HVStackProps
  extends VStackContract, PropsWithChildren<HTMLAttributes<HTMLDivElement>> {}

export function HVStack({
  gap = 'md',
  align = 'stretch',
  justify = 'start',
  reverse = false,
  className,
  style,
  children,
  ...props
}: HVStackProps) {
  const contract = { gap, align, justify, reverse }
  return (
    <div
      {...props}
      className={stackClassName('ui-v-stack', contract, className)}
      style={{ ...stackStyle(contract), ...style }}
    >
      {children}
    </div>
  )
}

// packages/web-components/src/h-v-stack.ts
import type { VStackContract } from '@demo/ui-core'
import { stackClassName, stackStyle } from '@demo/ui-core'
import { defineOnce } from './compound'
import { applyLayout, boolAttr } from './layout-shared'

export class HVStack extends HTMLElement {
  static observedAttributes = ['gap', 'align', 'justify', 'reverse']

  connectedCallback() {
    this.apply()
  }

  attributeChangedCallback() {
    this.apply()
  }

  private apply() {
    const props: VStackContract = {
      gap: (this.getAttribute('gap') as VStackContract['gap']) ?? 'md',
      align: (this.getAttribute('align') as VStackContract['align']) ?? 'stretch',
      justify: (this.getAttribute('justify') as VStackContract['justify']) ?? 'start',
      reverse: boolAttr(this, 'reverse', false),
    }
    applyLayout(this, stackClassName('ui-v-stack', props), stackStyle(props))
  }
}

export type HVStackProps = VStackContract
defineOnce('h-v-stack', HVStack)
