// packages/vue/src/HAccordion.vue
<script setup lang="ts">
import { Accordion } from '@ark-ui/vue/accordion'
import type { AccordionContract, AccordionItemContract, AccordionValueChangeDetails } from '@demo/ui-core'

export interface HAccordionItem extends AccordionItemContract<string> {}

withDefaults(defineProps<AccordionContract<string>>(), { multiple: false })
const emit = defineEmits<{ 'value-change': [details: AccordionValueChangeDetails] }>()
</script>

<template>
  <Accordion.Root
    :multiple="multiple"
    :default-value="defaultValue"
    :value="value"
    class="accordion"
    @value-change="emit('value-change', $event)"
  >
    <Accordion.Item v-for="item in items" :key="item.value" :value="item.value" class="accordion-item">
      <Accordion.ItemTrigger class="accordion-trigger">
        {{ item.title }}
        <Accordion.ItemIndicator>+</Accordion.ItemIndicator>
      </Accordion.ItemTrigger>
      <Accordion.ItemContent class="accordion-content">
        {{ item.content }}
      </Accordion.ItemContent>
    </Accordion.Item>
  </Accordion.Root>
</template>

// packages/react/src/HAccordion.tsx
import { Accordion as ArkAccordion } from '@ark-ui/react/accordion'
import type { AccordionContract, AccordionItemContract, AccordionValueChangeDetails } from '@demo/ui-core'

export interface HAccordionItem extends AccordionItemContract<React.ReactNode> {}

export interface HAccordionProps extends AccordionContract<React.ReactNode> {
  onValueChange?: (details: AccordionValueChangeDetails) => void
}

export function HAccordion({ items, multiple = false, defaultValue, value, onValueChange }: HAccordionProps) {
  return (
    <ArkAccordion.Root multiple={multiple} defaultValue={defaultValue} value={value} onValueChange={onValueChange} className="accordion">
      {items.map(item => (
        <ArkAccordion.Item key={item.value} value={item.value} className="accordion-item">
          <ArkAccordion.ItemTrigger className="accordion-trigger">
            {item.title}
            <ArkAccordion.ItemIndicator>+</ArkAccordion.ItemIndicator>
          </ArkAccordion.ItemTrigger>
          <ArkAccordion.ItemContent className="accordion-content">{item.content}</ArkAccordion.ItemContent>
        </ArkAccordion.Item>
      ))}
    </ArkAccordion.Root>
  )
}
