// packages/vue/src/HCheckbox.vue
<script setup lang="ts">
import { Checkbox } from '@ark-ui/vue/checkbox'
import type { CheckedChangeDetails, CheckboxContract } from '@demo/ui-core'

defineProps<CheckboxContract>()
const emit = defineEmits<{ 'checked-change': [details: CheckedChangeDetails] }>()
</script>

<template>
  <Checkbox.Root
    :checked="checked"
    :default-checked="defaultChecked"
    :disabled="disabled"
    @checked-change="emit('checked-change', { checked: Boolean($event.checked) })"
  >
    <Checkbox.Control>
      <Checkbox.Indicator>✓</Checkbox.Indicator>
    </Checkbox.Control>
    <Checkbox.Label>{{ label }}</Checkbox.Label>
    <Checkbox.HiddenInput />
  </Checkbox.Root>
</template>

// packages/react/src/HCheckbox.tsx
import { Checkbox as ArkCheckbox } from '@ark-ui/react/checkbox'
import type { CheckedChangeDetails, CheckboxContract } from '@demo/ui-core'

export interface HCheckboxProps extends CheckboxContract {
  onCheckedChange?: (details: CheckedChangeDetails) => void
}

export function HCheckbox({ label, onCheckedChange, ...props }: HCheckboxProps) {
  return (
    <ArkCheckbox.Root {...props} onCheckedChange={details => onCheckedChange?.({ checked: Boolean(details.checked) })}>
      <ArkCheckbox.Control>
        <ArkCheckbox.Indicator>✓</ArkCheckbox.Indicator>
      </ArkCheckbox.Control>
      <ArkCheckbox.Label>{label}</ArkCheckbox.Label>
      <ArkCheckbox.HiddenInput />
    </ArkCheckbox.Root>
  )
}
