// packages/web-components/src/h-container.ts
import type { ContainerContract } from '@demo/ui-core'
import { containerClassName, containerStyle } from '@demo/ui-core'
import { defineOnce } from './compound'
import { applyLayout, boolAttr } from './layout-shared'

export class HContainer extends HTMLElement {
  static observedAttributes = ['size', 'padded', 'center']

  connectedCallback() {
    this.apply()
  }

  attributeChangedCallback() {
    this.apply()
  }

  private apply() {
    const props: ContainerContract = {
      size: (this.getAttribute('size') as ContainerContract['size']) ?? 'xl',
      padded: boolAttr(this, 'padded', true),
      center: boolAttr(this, 'center', true),
    }
    applyLayout(this, containerClassName(props), containerStyle(props))
  }
}

export type HContainerProps = ContainerContract
defineOnce('h-container', HContainer)

// packages/react/src/HContainer.tsx
import type { HTMLAttributes, PropsWithChildren } from 'react'
import type { ContainerContract } from '@demo/ui-core'
import { containerClassName, containerStyle } from './layout-style'

export interface HContainerProps
  extends ContainerContract, PropsWithChildren<HTMLAttributes<HTMLDivElement>> {}

export function HContainer({
  size = 'xl',
  padded = true,
  center = true,
  className,
  style,
  children,
  ...props
}: HContainerProps) {
  const contract = { size, padded, center }
  return (
    <div
      {...props}
      className={containerClassName(contract, className)}
      style={{ ...containerStyle(contract), ...style }}
    >
      {children}
    </div>
  )
}
