// packages/vue/src/HEmpty.vue
<script setup lang="ts">
import type { EmptyContract } from '@demo/ui-core'

withDefaults(defineProps<EmptyContract<string>>(), {
  title: 'No data',
})
</script>

<template>
  <div class="ui-empty">
    <div class="ui-empty__icon" aria-hidden="true">○</div>
    <h3 v-if="title" class="ui-empty__title">{{ title }}</h3>
    <p v-if="description" class="ui-empty__description">{{ description }}</p>
    <div v-if="$slots.default" class="ui-empty__action">
      <slot />
    </div>
  </div>
</template>

// packages/react/src/HEmpty.tsx
import type { ReactNode } from 'react'
import type { EmptyContract } from '@demo/ui-core'

export interface HEmptyProps extends EmptyContract<ReactNode> {
  className?: string
  children?: ReactNode
}

export function HEmpty({ title = 'No data', description, children, className }: HEmptyProps) {
  return (
    <div className={['ui-empty', className].filter(Boolean).join(' ')}>
      <div className="ui-empty__icon" aria-hidden>○</div>
      {title ? <h3 className="ui-empty__title">{title}</h3> : null}
      {description ? <p className="ui-empty__description">{description}</p> : null}
      {children ? <div className="ui-empty__action">{children}</div> : null}
    </div>
  )
}
