// packages/vue/src/HNumberInput.vue
<script setup lang="ts">
import { NumberInput } from '@ark-ui/vue/number-input'
import type { NumberInputContract, ValueChangeDetails } from '@demo/ui-core'

defineProps<NumberInputContract>()
const emit = defineEmits<{ 'update:value': [value: string]; 'value-change': [details: ValueChangeDetails] }>()

function onValueChange(details: { value: string }) {
  emit('value-change', { value: details.value })
  emit('update:value', details.value)
}
</script>

<template>
  <NumberInput.Root
    class="ui-number-input"
    :value="value"
    :default-value="defaultValue"
    :min="min"
    :max="max"
    :step="step"
    :disabled="disabled"
    :read-only="readOnly"
    :required="required"
    :name="name"
    :invalid="Boolean(error)"
    @value-change="onValueChange"
  >
    <NumberInput.Label v-if="label" class="ui-field__label">{{ label }}</NumberInput.Label>
    <NumberInput.Control class="ui-number-input__control">
      <NumberInput.Input class="ui-number-input__input" />
      <div class="ui-number-input__triggers">
        <NumberInput.IncrementTrigger class="ui-number-input__trigger" type="button">+</NumberInput.IncrementTrigger>
        <NumberInput.DecrementTrigger class="ui-number-input__trigger" type="button">−</NumberInput.DecrementTrigger>
      </div>
    </NumberInput.Control>
    <span v-if="helperText && !error" class="ui-field__helper">{{ helperText }}</span>
    <span v-if="error" class="ui-field__error">{{ error }}</span>
  </NumberInput.Root>
</template>

// packages/react/src/HNumberInput.tsx
import { NumberInput } from '@ark-ui/react/number-input'
import type { NumberInputContract, ValueChangeDetails } from '@demo/ui-core'

export interface HNumberInputProps extends NumberInputContract {
  onValueChange?: (details: ValueChangeDetails) => void
}

export function HNumberInput({
  label,
  value,
  defaultValue,
  min,
  max,
  step,
  disabled,
  readOnly,
  required,
  name,
  error,
  helperText,
  onValueChange,
}: HNumberInputProps) {
  const invalid = Boolean(error)
  return (
    <NumberInput.Root
      className="ui-number-input"
      value={value}
      defaultValue={defaultValue}
      min={min}
      max={max}
      step={step}
      disabled={disabled}
      readOnly={readOnly}
      required={required}
      name={name}
      invalid={invalid}
      onValueChange={details => onValueChange?.({ value: details.value })}
    >
      {label ? <NumberInput.Label className="ui-field__label">{label}</NumberInput.Label> : null}
      <NumberInput.Control className="ui-number-input__control">
        <NumberInput.Input className="ui-number-input__input" />
        <div className="ui-number-input__triggers">
          <NumberInput.IncrementTrigger className="ui-number-input__trigger" type="button">
            +
          </NumberInput.IncrementTrigger>
          <NumberInput.DecrementTrigger className="ui-number-input__trigger" type="button">
            −
          </NumberInput.DecrementTrigger>
        </div>
      </NumberInput.Control>
      {helperText && !error ? <span className="ui-field__helper">{helperText}</span> : null}
      {error ? <span className="ui-field__error">{error}</span> : null}
    </NumberInput.Root>
  )
}
