// packages/vue/src/HPasswordInput.vue
<script setup lang="ts">
import { PasswordInput } from '@ark-ui/vue/password-input'
import type { PasswordInputContract, ValueChangeDetails } from '@demo/ui-core'

withDefaults(defineProps<PasswordInputContract>(), {
  autoComplete: 'current-password',
})
const emit = defineEmits<{ 'update:value': [value: string]; 'value-change': [details: ValueChangeDetails] }>()

function onInput(event: Event) {
  const value = (event.target as HTMLInputElement).value
  emit('update:value', value)
  emit('value-change', { value })
}
</script>

<template>
  <PasswordInput.Root
    class="ui-password-input"
    :disabled="disabled"
    :read-only="readOnly"
    :required="required"
    :invalid="Boolean(error)"
    :name="name"
    :auto-complete="autoComplete"
  >
    <PasswordInput.Label v-if="label" class="ui-field__label">{{ label }}</PasswordInput.Label>
    <PasswordInput.Control class="ui-password-input__control">
      <PasswordInput.Input
        class="ui-password-input__input"
        :value="value"
        :default-value="defaultValue"
        :placeholder="placeholder"
        @input="onInput"
      />
      <PasswordInput.VisibilityTrigger class="ui-password-input__trigger" type="button">
        <PasswordInput.Indicator class="ui-password-input__indicator" fallback="Show">
          Hide
        </PasswordInput.Indicator>
      </PasswordInput.VisibilityTrigger>
    </PasswordInput.Control>
    <span v-if="helperText && !error" class="ui-field__helper">{{ helperText }}</span>
    <span v-if="error" class="ui-field__error">{{ error }}</span>
  </PasswordInput.Root>
</template>

// packages/react/src/HPasswordInput.tsx
import { PasswordInput } from '@ark-ui/react/password-input'
import type { PasswordInputContract, ValueChangeDetails } from '@demo/ui-core'

export interface HPasswordInputProps extends PasswordInputContract {
  onValueChange?: (details: ValueChangeDetails) => void
}

/**
 * Password field with visibility toggle.
 * Zag PasswordInput owns visibility only; value is controlled via the input (MeshFlow-ready).
 */
export function HPasswordInput({
  label,
  value,
  defaultValue,
  placeholder,
  disabled,
  readOnly,
  required,
  name,
  error,
  helperText,
  autoComplete = 'current-password',
  onValueChange,
}: HPasswordInputProps) {
  const invalid = Boolean(error)
  return (
    <PasswordInput.Root
      className="ui-password-input"
      disabled={disabled}
      readOnly={readOnly}
      required={required}
      invalid={invalid}
      name={name}
      autoComplete={autoComplete}
    >
      {label ? <PasswordInput.Label className="ui-field__label">{label}</PasswordInput.Label> : null}
      <PasswordInput.Control className="ui-password-input__control">
        <PasswordInput.Input
          className="ui-password-input__input"
          value={value}
          defaultValue={defaultValue}
          placeholder={placeholder}
          onChange={event => onValueChange?.({ value: event.target.value })}
        />
        <PasswordInput.VisibilityTrigger className="ui-password-input__trigger" type="button">
          <PasswordInput.Indicator className="ui-password-input__indicator" fallback="Show">
            Hide
          </PasswordInput.Indicator>
        </PasswordInput.VisibilityTrigger>
      </PasswordInput.Control>
      {helperText && !error ? <span className="ui-field__helper">{helperText}</span> : null}
      {error ? <span className="ui-field__error">{error}</span> : null}
    </PasswordInput.Root>
  )
}
