// packages/vue/src/HSlider.vue
<script setup lang="ts">
import { Slider } from '@ark-ui/vue/slider'
import type { NumberValueChangeDetails, SliderContract } from '@demo/ui-core'

withDefaults(defineProps<SliderContract>(), {
  defaultValue: 0,
  min: 0,
  max: 100,
  step: 1,
})
const emit = defineEmits<{
  'update:value': [value: number]
  'value-change': [details: NumberValueChangeDetails]
}>()

function onValueChange(details: { value: number[] }) {
  const value = details.value[0] ?? 0
  emit('value-change', { value })
  emit('update:value', value)
}
</script>

<template>
  <Slider.Root
    class="ui-slider"
    :value="value === undefined ? undefined : [value]"
    :default-value="[defaultValue]"
    :min="min"
    :max="max"
    :step="step"
    :disabled="disabled"
    :name="name"
    @value-change="onValueChange"
  >
    <div class="ui-slider__header">
      <Slider.Label v-if="label" class="ui-field__label">{{ label }}</Slider.Label>
      <Slider.ValueText class="ui-slider__value" />
    </div>
    <Slider.Control class="ui-slider__control">
      <Slider.Track class="ui-slider__track">
        <Slider.Range class="ui-slider__range" />
      </Slider.Track>
      <Slider.Thumb :index="0" class="ui-slider__thumb">
        <Slider.HiddenInput />
      </Slider.Thumb>
    </Slider.Control>
  </Slider.Root>
</template>

// packages/react/src/HSlider.tsx
import { Slider } from '@ark-ui/react/slider'
import type { NumberValueChangeDetails, SliderContract } from '@demo/ui-core'

export interface HSliderProps extends SliderContract {
  onValueChange?: (details: NumberValueChangeDetails) => void
}

export function HSlider({
  label,
  value,
  defaultValue = 0,
  min = 0,
  max = 100,
  step = 1,
  disabled,
  name,
  onValueChange,
}: HSliderProps) {
  return (
    <Slider.Root
      className="ui-slider"
      value={value === undefined ? undefined : [value]}
      defaultValue={[defaultValue]}
      min={min}
      max={max}
      step={step}
      disabled={disabled}
      name={name}
      onValueChange={details => onValueChange?.({ value: details.value[0] ?? min })}
    >
      <div className="ui-slider__header">
        {label ? <Slider.Label className="ui-field__label">{label}</Slider.Label> : null}
        <Slider.ValueText className="ui-slider__value" />
      </div>
      <Slider.Control className="ui-slider__control">
        <Slider.Track className="ui-slider__track">
          <Slider.Range className="ui-slider__range" />
        </Slider.Track>
        <Slider.Thumb index={0} className="ui-slider__thumb">
          <Slider.HiddenInput />
        </Slider.Thumb>
      </Slider.Control>
    </Slider.Root>
  )
}
