// packages/vue/src/HTextarea.vue
<script setup lang="ts">
import { Field } from '@ark-ui/vue/field'
import type { TextareaContract, ValueChangeDetails } from '@demo/ui-core'

withDefaults(defineProps<TextareaContract & { class?: string }>(), {
  size: 'md',
  rows: 3,
})
const emit = defineEmits<{ 'update:value': [value: string]; 'value-change': [details: ValueChangeDetails] }>()

function onInput(event: Event) {
  const value = (event.target as HTMLTextAreaElement).value
  emit('update:value', value)
  emit('value-change', { value })
}
</script>

<template>
  <Field.Root
    class="ui-field"
    :class="[`ui-field--${size}`, $props.class]"
    :invalid="Boolean(error)"
    :required="required"
    :disabled="disabled"
  >
    <Field.Label v-if="label" class="ui-field__label">
      {{ label }}
      <span v-if="required" class="ui-field__required">*</span>
    </Field.Label>
    <Field.Textarea
      class="ui-textarea"
      :name="name"
      :placeholder="placeholder"
      :value="value"
      :default-value="defaultValue"
      :disabled="disabled"
      :readonly="readOnly"
      :required="required"
      :rows="rows"
      @input="onInput"
    />
    <Field.HelperText v-if="helperText && !error" class="ui-field__helper">{{ helperText }}</Field.HelperText>
    <Field.ErrorText v-if="error" class="ui-field__error">{{ error }}</Field.ErrorText>
  </Field.Root>
</template>

// packages/react/src/HTextarea.tsx
import type { TextareaHTMLAttributes } from 'react'
import { Field } from '@ark-ui/react/field'
import type { TextareaContract, ValueChangeDetails } from '@demo/ui-core'

export interface HTextareaProps
  extends TextareaContract,
    Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'value' | 'defaultValue' | 'size'> {
  onValueChange?: (details: ValueChangeDetails) => void
}

export function HTextarea({
  label,
  helperText,
  error,
  size = 'md',
  rows = 3,
  onValueChange,
  className,
  required,
  ...props
}: HTextareaProps) {
  const invalid = Boolean(error)
  return (
    <Field.Root
      className={['ui-field', `ui-field--${size}`, className].filter(Boolean).join(' ')}
      invalid={invalid}
      required={required}
      disabled={props.disabled}
    >
      {label ? (
        <Field.Label className="ui-field__label">
          {label}
          {required ? <span className="ui-field__required">*</span> : null}
        </Field.Label>
      ) : null}
      <Field.Textarea
        className="ui-textarea"
        rows={rows}
        {...props}
        onChange={event => {
          props.onChange?.(event)
          onValueChange?.({ value: event.target.value })
        }}
      />
      {helperText && !error ? <Field.HelperText className="ui-field__helper">{helperText}</Field.HelperText> : null}
      {error ? <Field.ErrorText className="ui-field__error">{error}</Field.ErrorText> : null}
    </Field.Root>
  )
}
