// packages/vue/src/HVStack.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { VStackContract } from '@demo/ui-core'
import { stackClassName, stackStyle } from '@demo/ui-core'

const props = withDefaults(defineProps<VStackContract & { class?: string }>(), {
  gap: 'md',
  align: 'stretch',
  justify: 'start',
  reverse: false,
  fillHeight: false,
})

const classes = computed(() => stackClassName('ui-v-stack', props, props.class))
const styles = computed(() => stackStyle(props))
</script>

<template>
  <div :class="classes" :style="styles">
    <slot />
  </div>
</template>

// packages/react/src/HVStack.tsx
import type { HTMLAttributes, PropsWithChildren } from 'react'
import type { VStackContract } from '@demo/ui-core'
import { stackClassName, stackStyle } from './layout-style'

export interface HVStackProps
  extends VStackContract, PropsWithChildren<HTMLAttributes<HTMLDivElement>> {}

export function HVStack({
  gap = 'md',
  align = 'stretch',
  justify = 'start',
  reverse = false,
  fillHeight = false,
  className,
  style,
  children,
  ...props
}: HVStackProps) {
  const contract = { gap, align, justify, reverse, fillHeight }
  return (
    <div
      {...props}
      className={stackClassName('ui-v-stack', contract, className)}
      style={{ ...stackStyle(contract), ...style }}
    >
      {children}
    </div>
  )
}
