// packages/react/src/HButton.tsx
import type { ButtonHTMLAttributes, PropsWithChildren } from 'react'
import type { ButtonContract } from '@demo/ui-core'

export interface HButtonProps extends ButtonContract, PropsWithChildren<ButtonHTMLAttributes<HTMLButtonElement>> {}

export function HButton({ variant = 'primary', size = 'md', className, ...props }: HButtonProps) {
  return <button {...props} className={['ui-button', `ui-button--${variant}`, `ui-button--${size}`, className].filter(Boolean).join(' ')} />
}

// packages/vue/src/HButton.vue
<script setup lang="ts">
import type { ButtonContract } from '@demo/ui-core'

withDefaults(defineProps<ButtonContract>(), { variant: 'primary', size: 'md' })
</script>

<template><button class="ui-button" :class="[`ui-button--${variant}`, `ui-button--${size}`]" :disabled="disabled"><slot /></button></template>
