// packages/react/src/HCard.tsx
import type { HTMLAttributes, PropsWithChildren, ReactNode } from 'react'
import type { CardContract } from '@demo/ui-core'

export interface HCardProps extends CardContract<ReactNode>, PropsWithChildren<Omit<HTMLAttributes<HTMLElement>, 'title'>> {}

export function HCard({ title, description, variant = 'surface', className, children, ...props }: HCardProps) {
  return (
    <section {...props} className={['ui-card', `ui-card--${variant}`, className].filter(Boolean).join(' ')}>
      {title || description ? (
        <header className="ui-card__header">
          {title ? <h3 className="ui-card__title">{title}</h3> : null}
          {description ? <p className="ui-card__description">{description}</p> : null}
        </header>
      ) : null}
      {children}
    </section>
  )
}

// packages/vue/src/HCard.vue
<script setup lang="ts">
import type { CardContract } from '@demo/ui-core'

withDefaults(defineProps<CardContract<string>>(), { variant: 'surface' })
</script>

<template>
  <section class="ui-card" :class="`ui-card--${variant}`">
    <header v-if="title || description" class="ui-card__header">
      <h3 v-if="title" class="ui-card__title">{{ title }}</h3>
      <p v-if="description" class="ui-card__description">{{ description }}</p>
    </header>
    <slot />
  </section>
</template>
