// packages/react/src/HContainer.tsx
import type { HTMLAttributes, PropsWithChildren } from 'react'
import type { ContainerContract } from '@demo/ui-core'
import { containerClassName, containerStyle } from './layout-style'

export interface HContainerProps
  extends ContainerContract, PropsWithChildren<HTMLAttributes<HTMLDivElement>> {}

export function HContainer({
  size = 'xl',
  padded = true,
  center = true,
  className,
  style,
  children,
  ...props
}: HContainerProps) {
  const contract = { size, padded, center }
  return (
    <div
      {...props}
      className={containerClassName(contract, className)}
      style={{ ...containerStyle(contract), ...style }}
    >
      {children}
    </div>
  )
}

// packages/vue/src/HContainer.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { ContainerContract } from '@demo/ui-core'
import { containerClassName, containerStyle } from '@demo/ui-core'

const props = withDefaults(defineProps<ContainerContract & { class?: string }>(), {
  size: 'xl',
  padded: true,
  center: true,
})

const classes = computed(() => containerClassName(props, props.class))
const styles = computed(() => containerStyle(props))
</script>

<template>
  <div :class="classes" :style="styles">
    <slot />
  </div>
</template>
