// packages/react/src/HDialog.tsx
import type { ReactNode } from 'react'
import { Dialog as ArkDialog } from '@ark-ui/react/dialog'
import type { DialogContract, OpenChangeDetails } from '@demo/ui-core'

export interface HDialogProps extends DialogContract<ReactNode> {
  onOpenChange?: (details: OpenChangeDetails) => void
}

/**
 * Ark Dialog + Presence. Theme CSS animates [data-state=open|closed]
 * (fade backdrop + scale/fade content).
 */
export function HDialog({
  trigger,
  title,
  description,
  children,
  onOpenChange,
  lazyMount = true,
  unmountOnExit = true,
  skipAnimationOnMount = false,
  ...props
}: HDialogProps) {
  return (
    <ArkDialog.Root
      {...props}
      onOpenChange={onOpenChange}
      lazyMount={lazyMount}
      unmountOnExit={unmountOnExit}
      skipAnimationOnMount={skipAnimationOnMount}
    >
      {trigger ? <ArkDialog.Trigger className="ui-button ui-button--secondary">{trigger}</ArkDialog.Trigger> : null}
      <ArkDialog.Backdrop className="ui-dialog__backdrop" />
      <ArkDialog.Positioner className="ui-dialog__positioner">
        <ArkDialog.Content className="dialog-content ui-dialog__content">
          <ArkDialog.Title className="ui-dialog__title">{title}</ArkDialog.Title>
          {description ? (
            <ArkDialog.Description className="ui-dialog__description">{description}</ArkDialog.Description>
          ) : null}
          {children}
          <ArkDialog.CloseTrigger className="ui-button ui-button--secondary">Close</ArkDialog.CloseTrigger>
        </ArkDialog.Content>
      </ArkDialog.Positioner>
    </ArkDialog.Root>
  )
}

// packages/vue/src/HDialog.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Dialog } from '@ark-ui/vue/dialog'
import type { DialogContract, OpenChangeDetails } from '@demo/ui-core'

const props = withDefaults(defineProps<DialogContract<string>>(), { defaultOpen: false })
const emit = defineEmits<{ 'open-change': [details: OpenChangeDetails] }>()

/** Same controlled-open fix as HDrawer: only pass `open` when parent controls it. */
const rootProps = computed(() => {
  const result: Record<string, unknown> = {
    defaultOpen: props.defaultOpen,
    lazyMount: true,
    unmountOnExit: true,
    skipAnimationOnMount: false,
  }
  if (props.open !== undefined) result.open = props.open
  return result
})
</script>

<template>
  <Dialog.Root v-bind="rootProps" @open-change="emit('open-change', $event)">
    <Dialog.Trigger class="ui-button ui-button--secondary">
      {{ trigger }}
    </Dialog.Trigger>
    <Dialog.Backdrop class="ui-dialog__backdrop" />
    <Dialog.Positioner class="ui-dialog__positioner">
      <Dialog.Content class="dialog-content ui-dialog__content">
        <Dialog.Title class="ui-dialog__title">{{ title }}</Dialog.Title>
        <Dialog.Description v-if="description" class="ui-dialog__description">
          {{ description }}
        </Dialog.Description>
        <slot />
        <Dialog.CloseTrigger class="ui-button ui-button--secondary">
          Close
        </Dialog.CloseTrigger>
      </Dialog.Content>
    </Dialog.Positioner>
  </Dialog.Root>
</template>
