// packages/react/src/HDrawer.tsx
import type { CSSProperties, ReactNode } from 'react'
import { Drawer as ArkDrawer } from '@ark-ui/react/drawer'
import type { DrawerContract, DrawerPlacement, OpenChangeDetails } from '@demo/ui-core'
import { drawerSwipeDirection } from '@demo/ui-core'

export interface HDrawerProps extends DrawerContract<ReactNode> {
  onOpenChange?: (details: OpenChangeDetails) => void
}

/**
 * Ark Drawer + Presence. Theme CSS animates [data-state=open|closed].
 * lazyMount/unmountOnExit keep enter/exit animations reliable.
 */
export function HDrawer({
  trigger,
  title,
  description,
  children,
  placement = 'right',
  size = '360px',
  onOpenChange,
  lazyMount = true,
  unmountOnExit = true,
  skipAnimationOnMount = false,
  ...props
}: HDrawerProps) {
  const swipeDirection = drawerSwipeDirection(placement)
  const panelStyle = {
    ['--ui-drawer-size' as string]: size,
  } as CSSProperties

  return (
    <ArkDrawer.Root
      {...props}
      swipeDirection={swipeDirection}
      onOpenChange={onOpenChange}
      lazyMount={lazyMount}
      unmountOnExit={unmountOnExit}
      skipAnimationOnMount={skipAnimationOnMount}
    >
      {trigger ? <ArkDrawer.Trigger className="ui-button ui-button--secondary">{trigger}</ArkDrawer.Trigger> : null}
      <ArkDrawer.Backdrop className="ui-drawer__backdrop" />
      <ArkDrawer.Positioner
        className={['ui-drawer__positioner', `ui-drawer__positioner--${placement}`].join(' ')}
        data-placement={placement}
      >
        <ArkDrawer.Content
          className={['ui-drawer__content', `ui-drawer__content--${placement}`].join(' ')}
          style={panelStyle}
          data-placement={placement}
        >
          <header className="ui-drawer__header">
            <ArkDrawer.Title className="ui-drawer__title">{title}</ArkDrawer.Title>
            <ArkDrawer.CloseTrigger className="ui-button ui-button--ghost ui-drawer__close" type="button">
              Close
            </ArkDrawer.CloseTrigger>
          </header>
          {description ? (
            <ArkDrawer.Description className="ui-drawer__description">{description}</ArkDrawer.Description>
          ) : null}
          <div className="ui-drawer__body">{children}</div>
        </ArkDrawer.Content>
      </ArkDrawer.Positioner>
    </ArkDrawer.Root>
  )
}

export type { DrawerPlacement }

// packages/vue/src/HDrawer.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Drawer } from '@ark-ui/vue/drawer'
import type { DrawerContract, OpenChangeDetails } from '@demo/ui-core'
import { drawerSwipeDirection } from '@demo/ui-core'

const props = withDefaults(defineProps<DrawerContract<string> & { class?: string }>(), {
  defaultOpen: false,
  placement: 'right',
  size: '360px',
})

const emit = defineEmits<{ 'open-change': [details: OpenChangeDetails] }>()

const swipeDirection = computed(() => drawerSwipeDirection(props.placement))
const rootProps = computed(() => {
  const result: Record<string, unknown> = {
    defaultOpen: props.defaultOpen,
    swipeDirection: swipeDirection.value,
    lazyMount: true,
    unmountOnExit: true,
    skipAnimationOnMount: false,
  }
  if (props.open !== undefined) result.open = props.open
  return result
})
const panelStyle = computed(() => ({ '--ui-drawer-size': props.size }))
const positionerClass = computed(
  () => `ui-drawer__positioner ui-drawer__positioner--${props.placement}`,
)
const contentClass = computed(
  () => `ui-drawer__content ui-drawer__content--${props.placement}`,
)
</script>

<template>
  <!-- Presence: lazy-mount + unmount-on-exit so CSS [data-state] enter/exit animations run -->
  <Drawer.Root
    v-bind="rootProps"
    @open-change="emit('open-change', $event)"
  >
    <Drawer.Trigger class="ui-button ui-button--secondary">
      {{ trigger }}
    </Drawer.Trigger>
    <Drawer.Backdrop class="ui-drawer__backdrop" />
    <Drawer.Positioner :class="positionerClass" :data-placement="props.placement">
      <Drawer.Content
        :class="contentClass"
        :style="panelStyle"
        :data-placement="props.placement"
      >
        <header class="ui-drawer__header">
          <Drawer.Title class="ui-drawer__title">{{ title }}</Drawer.Title>
          <Drawer.CloseTrigger class="ui-button ui-button--ghost ui-drawer__close" type="button">
            Close
          </Drawer.CloseTrigger>
        </header>
        <Drawer.Description v-if="description" class="ui-drawer__description">
          {{ description }}
        </Drawer.Description>
        <div class="ui-drawer__body">
          <slot />
        </div>
      </Drawer.Content>
    </Drawer.Positioner>
  </Drawer.Root>
</template>
