// packages/react/src/HGrid.tsx
import type { HTMLAttributes, PropsWithChildren } from 'react'
import type { GridContract } from '@demo/ui-core'
import { gridClassName, gridStyle } from './layout-style'

export interface HGridProps extends GridContract, PropsWithChildren<HTMLAttributes<HTMLDivElement>> {}

export function HGrid({
  columns = 'auto-fit',
  minChildWidth = '240px',
  gap = 'md',
  rowGap,
  columnGap,
  equalHeight = false,
  className,
  style,
  children,
  ...props
}: HGridProps) {
  const contract = { columns, minChildWidth, gap, rowGap, columnGap, equalHeight }
  return (
    <div
      {...props}
      className={gridClassName(contract, className)}
      style={{ ...gridStyle(contract), ...style }}
    >
      {children}
    </div>
  )
}

// packages/vue/src/HGrid.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { GridContract } from '@demo/ui-core'
import { gridClassName, gridStyle } from '@demo/ui-core'

const props = withDefaults(defineProps<GridContract & { class?: string }>(), {
  columns: 'auto-fit',
  minChildWidth: '240px',
  gap: 'md',
  equalHeight: false,
})

const classes = computed(() => gridClassName(props, props.class))
const styles = computed(() => gridStyle(props))
</script>

<template>
  <div :class="classes" :style="styles">
    <slot />
  </div>
</template>
