// packages/react/src/HRadioGroup.tsx
import { RadioGroup } from '@ark-ui/react/radio-group'
import type { RadioGroupContract, ValueChangeDetails } from '@demo/ui-core'

export interface HRadioGroupProps extends RadioGroupContract {
  onValueChange?: (details: ValueChangeDetails) => void
}

export function HRadioGroup({
  items,
  value,
  defaultValue,
  disabled,
  name,
  label,
  onValueChange,
}: HRadioGroupProps) {
  return (
    <RadioGroup.Root
      className="ui-radio-group"
      value={value}
      defaultValue={defaultValue}
      disabled={disabled}
      name={name}
      onValueChange={details => onValueChange?.({ value: details.value ?? '' })}
    >
      {label ? <RadioGroup.Label className="ui-field__label">{label}</RadioGroup.Label> : null}
      <div className="ui-radio-group__items">
        {items.map(item => (
          <RadioGroup.Item key={item.value} value={item.value} disabled={item.disabled} className="ui-radio">
            <RadioGroup.ItemControl className="ui-radio__control" />
            <RadioGroup.ItemText className="ui-radio__label">{item.label}</RadioGroup.ItemText>
            <RadioGroup.ItemHiddenInput />
          </RadioGroup.Item>
        ))}
      </div>
    </RadioGroup.Root>
  )
}

// packages/vue/src/HRadioGroup.vue
<script setup lang="ts">
import { RadioGroup } from '@ark-ui/vue/radio-group'
import type { RadioGroupContract, ValueChangeDetails } from '@demo/ui-core'

/**
 * Ark Vue radio uses modelValue for controlled state (not `value`).
 * We still expose Core contract prop name `value` and map it here.
 */
defineProps<RadioGroupContract>()
const emit = defineEmits<{
  'value-change': [details: ValueChangeDetails]
  'update:value': [value: string]
}>()

function onValueChange(details: { value: string | null }) {
  const v = details.value ?? ''
  emit('value-change', { value: v })
  emit('update:value', v)
}
</script>

<template>
  <RadioGroup.Root
    class="ui-radio-group"
    :model-value="value"
    :default-value="defaultValue"
    :disabled="disabled"
    :name="name"
    @value-change="onValueChange"
  >
    <RadioGroup.Label v-if="label" class="ui-field__label">{{ label }}</RadioGroup.Label>
    <div class="ui-radio-group__items">
      <RadioGroup.Item
        v-for="item in items"
        :key="item.value"
        :value="item.value"
        :disabled="item.disabled"
        class="ui-radio"
      >
        <RadioGroup.ItemControl class="ui-radio__control" />
        <RadioGroup.ItemText class="ui-radio__label">{{ item.label }}</RadioGroup.ItemText>
        <RadioGroup.ItemHiddenInput />
      </RadioGroup.Item>
    </div>
  </RadioGroup.Root>
</template>
