// packages/react/src/HSkeleton.tsx
import type { HTMLAttributes } from 'react'
import type { SkeletonContract } from '@demo/ui-core'

export interface HSkeletonProps extends SkeletonContract, HTMLAttributes<HTMLDivElement> {}

export function HSkeleton({
  width = '100%',
  height = '1rem',
  circle,
  animated = true,
  className,
  style,
  ...props
}: HSkeletonProps) {
  return (
    <div
      {...props}
      className={['ui-skeleton', circle ? 'ui-skeleton--circle' : '', animated ? 'ui-skeleton--animated' : '', className].filter(Boolean).join(' ')}
      style={{ width: circle ? height : width, height, ...style }}
      aria-hidden
    />
  )
}

// packages/vue/src/HSkeleton.vue
<script setup lang="ts">
import type { SkeletonContract } from '@demo/ui-core'

withDefaults(defineProps<SkeletonContract>(), {
  width: '100%',
  height: '1rem',
  animated: true,
})
</script>

<template>
  <div
    class="ui-skeleton"
    :class="{ 'ui-skeleton--circle': circle, 'ui-skeleton--animated': animated }"
    :style="{ width: circle ? height : width, height }"
    aria-hidden="true"
  />
</template>
