// packages/react/src/HSpacer.tsx
import type { HTMLAttributes } from 'react'
import type { SpacerContract } from '@demo/ui-core'
import { spacerClassName, spacerStyle } from './layout-style'

export interface HSpacerProps extends SpacerContract, HTMLAttributes<HTMLDivElement> {}

export function HSpacer({
  size = 'md',
  grow = true,
  className,
  style,
  ...props
}: HSpacerProps) {
  const contract = { size, grow }
  return (
    <div
      {...props}
      aria-hidden
      className={spacerClassName(contract, className)}
      style={{ ...spacerStyle(contract), ...style }}
    />
  )
}

// packages/vue/src/HSpacer.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { SpacerContract } from '@demo/ui-core'
import { spacerClassName, spacerStyle } from '@demo/ui-core'

const props = withDefaults(defineProps<SpacerContract & { class?: string }>(), {
  size: 'md',
  grow: true,
})

const classes = computed(() => spacerClassName(props, props.class))
const styles = computed(() => spacerStyle(props))
</script>

<template>
  <div :class="classes" :style="styles" aria-hidden="true" />
</template>
