// packages/react/src/HStack.tsx
import type { HTMLAttributes, PropsWithChildren } from 'react'
import type { StackContract } from '@demo/ui-core'
import { stackClassName, stackStyle } from './layout-style'

export interface HStackProps extends StackContract, PropsWithChildren<HTMLAttributes<HTMLDivElement>> {}

export function HStack({
  gap = 'md',
  align = 'stretch',
  justify = 'start',
  wrap = false,
  stackBelow = 'never',
  reverse = false,
  className,
  style,
  children,
  ...props
}: HStackProps) {
  const contract = { gap, align, justify, wrap, stackBelow, reverse }
  return (
    <div
      {...props}
      className={stackClassName('ui-stack', contract, className, wrap)}
      style={{ ...stackStyle(contract), ...style }}
    >
      {children}
    </div>
  )
}

// packages/vue/src/HStack.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { StackContract } from '@demo/ui-core'
import { stackClassName, stackStyle } from '@demo/ui-core'

const props = withDefaults(defineProps<StackContract & { class?: string }>(), {
  gap: 'md',
  align: 'stretch',
  justify: 'start',
  wrap: false,
  stackBelow: 'never',
  reverse: false,
})

const classes = computed(() => stackClassName('ui-stack', props, props.class, props.wrap))
const styles = computed(() => stackStyle(props))
</script>

<template>
  <div :class="classes" :style="styles">
    <slot />
  </div>
</template>
