// packages/react/src/HToggle.tsx
import { Switch } from '@ark-ui/react/switch'
import type { ReactNode } from 'react'
import type { CheckedChangeDetails, ToggleContract } from '@demo/ui-core'

export interface HToggleProps extends ToggleContract {
  onCheckedChange?: (details: CheckedChangeDetails) => void
  children?: ReactNode
}

/** React renderer: Ark UI owns the interaction state machine. */
export function HToggle({ children, onCheckedChange, ...props }: HToggleProps) {
  return (
    <Switch.Root {...props} onCheckedChange={onCheckedChange}>
      <Switch.Control><Switch.Thumb /></Switch.Control>
      <Switch.Label>{children}</Switch.Label>
      <Switch.HiddenInput />
    </Switch.Root>
  )
}

// packages/vue/src/HToggle.vue
<script setup lang="ts">
import { Switch } from '@ark-ui/vue/switch'
import type { CheckedChangeDetails, ToggleContract } from '@demo/ui-core'

defineProps<ToggleContract>()
const emit = defineEmits<{ 'checked-change': [details: CheckedChangeDetails] }>()
</script>

<!-- Vue renderer: Ark UI owns the interaction state machine. -->
<template>
  <Switch.Root
    :checked="checked"
    :default-checked="defaultChecked"
    :disabled="disabled"
    @checked-change="emit('checked-change', $event)"
  >
    <Switch.Control><Switch.Thumb /></Switch.Control>
    <Switch.Label><slot /></Switch.Label>
    <Switch.HiddenInput />
  </Switch.Root>
</template>
