// packages/react/src/HTooltip.tsx
import type { ReactNode } from 'react'
import { Tooltip } from '@ark-ui/react/tooltip'
import type { OpenChangeDetails, TooltipContract } from '@demo/ui-core'

export interface HTooltipProps extends TooltipContract<ReactNode> {
  children: ReactNode
  onOpenChange?: (details: OpenChangeDetails) => void
}

export function HTooltip({
  content,
  children,
  open,
  defaultOpen,
  disabled,
  positioning = 'top',
  onOpenChange,
}: HTooltipProps) {
  return (
    <Tooltip.Root
      open={open}
      defaultOpen={defaultOpen}
      disabled={disabled}
      positioning={{ placement: positioning }}
      onOpenChange={details => onOpenChange?.({ open: details.open })}
    >
      <Tooltip.Trigger asChild>{children}</Tooltip.Trigger>
      <Tooltip.Positioner>
        <Tooltip.Content className="ui-tooltip">{content}</Tooltip.Content>
      </Tooltip.Positioner>
    </Tooltip.Root>
  )
}

// packages/vue/src/HTooltip.vue
<script setup lang="ts">
import { Tooltip } from '@ark-ui/vue/tooltip'
import type { OpenChangeDetails, TooltipContract } from '@demo/ui-core'

withDefaults(defineProps<TooltipContract<string>>(), {
  positioning: 'top',
})

const emit = defineEmits<{ 'open-change': [details: OpenChangeDetails] }>()
</script>

<template>
  <Tooltip.Root
    :open="open"
    :default-open="defaultOpen"
    :disabled="disabled"
    :positioning="{ placement: positioning }"
    @open-change="details => emit('open-change', { open: details.open })"
  >
    <Tooltip.Trigger class="ui-tooltip-trigger">
      <slot />
    </Tooltip.Trigger>
    <Tooltip.Positioner>
      <Tooltip.Content class="ui-tooltip">{{ content }}</Tooltip.Content>
    </Tooltip.Positioner>
  </Tooltip.Root>
</template>
